### ISSUE TITLE
Tests are inconsistent and require ordering.

### ISSUE THREAD

**Issue by WMagnus** [revaturelabs/cms-content-service#95]
Suggested fixes include merging tests and handling assertion at the end of test runtime.

**Comment by WMagnus** [comment]
Fixed for the new TimeGraphServiceTest in feature-reports-time-graph branch. Others to follow.

**Comment by carolynrehm** [comment]
All issues are managed in the [meta repo](https://github.com/revaturelabs/cms-meta). Please move this issue there.
